name = "MomentMatching"
uuid = "a67aff5b-0ccc-47d5-9c4f-fef2ba9c9aa3"
authors = ["Gualtiero Azzalini", "Zoltan Racz"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
